name: Remote SSH Command with Docker
on: [push]
jobs:
  build:
    name: Build and Deploy Docker Container
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Execute remote SSH commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd CI-CD-GITHUB-ACTIONS/
          git pull origin main || exit 1
          sudo -S docker stop api-golang
          sudo -S docker rm api-golang
          sudo -S docker rmi api-golang:latest
          sudo -S docker build -t api-golang:latest .
          sudo -S docker run -d --name api-golang -p 7777:7777 api-golang:latest
